### ISSUE TITLE
tiles vs. time progress normalization

### ISSUE THREAD

**Issue by sbailey** [sbailey/surveyqa#10]
Something is wrong in the normalization and trend lines for the tiles vs. time plot:
<img width="405" alt="image" src="https://user-images.githubusercontent.com/218471/53895454-51958d80-3fef-11e9-93fb-17186c3d1ca2.png">
In this case, there should be 3 trend lines, one for each of DARK, GRAY, and BRIGHT with different numbers of total tiles after 5 years for each program:
```
In [5]: for p in set(t['PROGRAM']):
   ...:     print(p, np.count_nonzero(t['PROGRAM'] == p))
   ...:     
BRIGHT 6028
GRAY 2005
DARK 8038
```
It also looks like the plot is showing the number of exposures for each program instead of the number of tiles:
```
In [8]: for p in set(exp['PROGRAM']):
   ...:     ii = exp['PROGRAM'] == p
   ...:     nexp = np.count_nonzero(ii)
   ...:     ntiles = len(set(exp['TILEID'][ii]))
   ...:     print(p, nexp, ntiles)
   ...:     
CALIB 810 1
GRAY 850 296
BRIGHT 1703 785
DARK 4093 1595
```
e.g. the DARK line should have reached 1595, not 4093.

**Comment by williyamshoe** [comment]
I see the problem; I did make a new table without repeated tiles, but continued using the full exposures table when making the plot. I have fixed it now in the new branch, and added separate "ideal lines" for DARK, GRAY, and BRIGHT.
