### ISSUE TITLE
Nightly skypath plots

### ISSUE THREAD

**Issue by rdoshi99** [sbailey/surveyqa#34]
The hover tool of the nightly skypath plot uses the figure's intrinsic coordinate system ($x, $y) to represent the RA and DEC
I was checking them against the RA and DEC recorded in the data source, and they are similar but not quite exact
Is this something which needs to be updated?

**Comment by sbailey** [comment]
Good catch.  It would indeed be better to use the real RA,dec, not the $x, $y of the cursor (which could be on the edge of the tile point, not the RA,dec of the center of the tile).

**Comment by sbailey** [comment]
fixed in PR #38
