### ISSUE TITLE
Feedback on survey progress plots

### ISSUE THREAD

**Issue by sbailey** [sbailey/surveyqa#5]
Suggestions for survey progress plots:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/218471/53839039-bb605980-3f53-11e9-8677-39eb428e7319.png">

* Progress should be "Fraction" 0-1 or "Percentage" 0-100.
* Progress should be normalized to the full set of tiles, not just the tiles observed to date.  i.e. 200 days into the survey we shouldn't be at "1" yet.
* Add light gray progress line for what we would have achieved if we were perfectly on schedule to finish in 5 years (i.e. a straight line from (startdate,0) to (startdate+5years, 1).
    * on-schedule trend lines for the #tiles vs. time would be normalized to the total number of tiles in each program
* Date axis will need work to be readable

**Comment by williyamshoe** [comment]
Hi, thanks for the feedback! I have just fixed these issues and pushed the changes. If there are still issues, please tell me!
