### ISSUE TITLE
gridlines vs. no gridlines for summary page histograms

### ISSUE THREAD

**Issue by ana-lyons** [sbailey/surveyqa#58]
<img width="1300" alt="Screen Shot 2019-04-15 at 4 34 21 PM" src="https://user-images.githubusercontent.com/47259815/56172027-7db40f00-5f9c-11e9-976b-580c9583ec6a.png">
<img width="1293" alt="Screen Shot 2019-04-15 at 4 33 10 PM" src="https://user-images.githubusercontent.com/47259815/56172031-80166900-5f9c-11e9-96c2-01dc3cb0b6ab.png">

which looks best?

**Comment by sbailey** [comment]
Group consensus was to keep the gridlines on the histograms for visual consistency with the other plots on the page where the gridlines are more specifically useful.
