### ISSUE TITLE
Feedback on summary histograms

### ISSUE THREAD

**Issue by sbailey** [sbailey/surveyqa#6]
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/218471/53839949-0a0ef300-3f56-11e9-8a6c-c499c9f38471.png">

Overall looks good.  A few comments:
* no need to specify "all non-calib exposures" in title (which runs out of space anyway)
* # exposures per tile is an integer quantity, so pick a binning where the bins are 1 unit wide.

**Comment by williyamshoe** [comment]
Hi, thanks for the feedback! I have just fixed these issues and pushed the changes. If there are still issues, please tell me!
